---@class Gruvbox
local Gruvbox = {}

Gruvbox.config = {
  terminal_colors = true,
  undercurl = true,
  underline = true,
  bold = true,
  italic = {
    strings = false,
    emphasis = true,
    comments = true,
    operators = false,
    folds = true,
  },
  strikethrough = true,
  invert_selection = false,
  invert_signs = false,
  invert_tabline = false,
  invert_intend_guides = false,
  inverse = true,
  contrast = "medium",
  palette_overrides = {},
  overrides = {},
  dim_inactive = false,
  transparent_mode = false,
}

---get a hex list of gruvbox colors based on current bg and constrast config
---@param config GruvboxConfig
local function get_palette(config)
  ---@type table<"dark"|"light", GruvboxPalette>
  local palette_groups = {
    -- stylua: ignore
    dark = {
      bg0_hard        = "#1d2021",
      bg0             = "#282828",
      bg0_soft        = "#32302f",
      bg1             = "#3c3836",
      bg2             = "#504945",
      bg3             = "#665c54",
      bg4             = "#7c6f64",
      gray            = "#928374",
      fg4             = "#a89984",
      fg3             = "#bdae93",
      fg2             = "#d5c4a1",
      fg1             = "#ebdbb2",
      fg0             = "#fbf1c7",
      line0           = "#665c54",
      line1           = "#605943",
      line2           = "#403f30",
      line3           = "#373433",
      red             = "#fb4934",
      green           = "#b8bb26",
      yellow          = "#fabd2f",
      blue            = "#83a598",
      purple          = "#d3869b",
      aqua            = "#8ec07c",
      orange          = "#fe8019",
      neutral_red     = "#cc241d",
      neutral_green   = "#98971a",
      neutral_yellow  = "#d79921",
      neutral_blue    = "#458588",
      neutral_purple  = "#b16286",
      neutral_aqua    = "#689d6a",
      neutral_orange  = "#d65d0e",
      dim_red_hard    = "#792329",
      dim_red         = "#722529",
      dim_red_soft    = "#7b2c2f",
      dim_green_hard  = "#5a633a",
      dim_green       = "#62693e",
      dim_green_soft  = "#686d43",
      dim_aqua_hard   = "#3e4934",
      dim_aqua        = "#49503b",
      dim_aqua_soft   = "#525742",
    },
    -- stylua: ignore
    light = {
      bg0_hard        = "#f9f5d7",
      bg0             = "#fbf1c7",
      bg0_soft        = "#f2e5bc",
      bg1             = "#ebdbb2",
      bg2             = "#d5c4a1",
      bg3             = "#bdae93",
      bg4             = "#a89984",
      gray            = "#928374",
      fg4             = "#7c6f64",
      fg3             = "#665c54",
      fg2             = "#504945",
      fg1             = "#3c3836",
      fg0             = "#282828",
      line0           = "#bdae93",
      line1           = "#b7a88d",
      line2           = "#e0cfa0",
      line3           = "#eeddb7",
      red             = "#9d0006",
      green           = "#79740e",
      yellow          = "#b57614",
      blue            = "#076678",
      purple          = "#8f3f71",
      aqua            = "#427b58",
      orange          = "#af3a03",
      neutral_red     = "#cc241d",
      neutral_green   = "#98971a",
      neutral_yellow  = "#d79921",
      neutral_blue    = "#458588",
      neutral_purple  = "#b16286",
      neutral_aqua    = "#689d6a",
      neutral_orange  = "#d65d0e",
      dim_red_hard    = "#fc9690",
      dim_red         = "#fc9487",
      dim_red_soft    = "#f78b7f",
      dim_green_hard  = "#d3d6a5",
      dim_green       = "#d5d39b",
      dim_green_soft  = "#cecb94",
      dim_aqua_hard   = "#e6e9c1",
      dim_aqua        = "#e8e5b5",
      dim_aqua_soft   = "#e1dbac",
    },
  }

  local bg = vim.o.background
  local contrast = config.contrast
  local palette = palette_groups[bg]

  for color, hex in pairs(config.palette_overrides) do
    palette[color] = hex
  end

  if contrast ~= nil and contrast ~= "medium" then
    palette.bg0 = palette["bg0_" .. contrast]
    palette.dim_red = palette["dim_red_" .. contrast]
    palette.dim_green = palette["dim_green_" .. contrast]
    palette.dim_aqua = palette["dim_aqua_" .. contrast]
  end

  return palette
end

---@param c GruvboxConfig
---@param p GruvboxPalette
local function build_hls(c, p)
  local groups = {
    GruvboxFg0 = { fg = p.fg0 },
    GruvboxFg1 = { fg = p.fg1 },
    GruvboxFg2 = { fg = p.fg2 },
    GruvboxFg3 = { fg = p.fg3 },
    GruvboxFg4 = { fg = p.fg4 },
    GruvboxGray = { fg = p.gray },
    GruvboxBg0 = { fg = p.bg0 },
    GruvboxBg1 = { fg = p.bg1 },
    GruvboxBg2 = { fg = p.bg2 },
    GruvboxBg3 = { fg = p.bg3 },
    GruvboxBg4 = { fg = p.bg4 },
    GruvboxRed = { fg = p.red },
    GruvboxRedBold = { fg = p.red, bold = c.bold },
    GruvboxGreen = { fg = p.green },
    GruvboxGreenBold = { fg = p.green, bold = c.bold },
    GruvboxYellow = { fg = p.yellow },
    GruvboxYellowBold = { fg = p.yellow, bold = c.bold },
    GruvboxBlue = { fg = p.blue },
    GruvboxBlueBold = { fg = p.blue, bold = c.bold },
    GruvboxPurple = { fg = p.purple },
    GruvboxPurpleBold = { fg = p.purple, bold = c.bold },
    GruvboxAqua = { fg = p.aqua },
    GruvboxAquaBold = { fg = p.aqua, bold = c.bold },
    GruvboxOrange = { fg = p.orange },
    GruvboxOrangeBold = { fg = p.orange, bold = c.bold },
    GruvboxRedSign = c.transparent_mode and { fg = p.red, reverse = c.invert_signs }
      or { fg = p.red, bg = p.bg1, reverse = c.invert_signs },
    GruvboxGreenSign = c.transparent_mode and { fg = p.green, reverse = c.invert_signs }
      or { fg = p.green, bg = p.bg1, reverse = c.invert_signs },
    GruvboxYellowSign = c.transparent_mode and { fg = p.yellow, reverse = c.invert_signs }
      or { fg = p.yellow, bg = p.bg1, reverse = c.invert_signs },
    GruvboxBlueSign = c.transparent_mode and { fg = p.blue, reverse = c.invert_signs }
      or { fg = p.blue, bg = p.bg1, reverse = c.invert_signs },
    GruvboxPurpleSign = c.transparent_mode and { fg = p.purple, reverse = c.invert_signs }
      or { fg = p.purple, bg = p.bg1, reverse = c.invert_signs },
    GruvboxAquaSign = c.transparent_mode and { fg = p.aqua, reverse = c.invert_signs }
      or { fg = p.aqua, bg = p.bg1, reverse = c.invert_signs },
    GruvboxOrangeSign = c.transparent_mode and { fg = p.orange, reverse = c.invert_signs }
      or { fg = p.orange, bg = p.bg1, reverse = c.invert_signs },
    GruvboxRedUnderline = { undercurl = c.undercurl, sp = p.red },
    GruvboxGreenUnderline = { undercurl = c.undercurl, sp = p.green },
    GruvboxYellowUnderline = { undercurl = c.undercurl, sp = p.yellow },
    GruvboxBlueUnderline = { undercurl = c.undercurl, sp = p.blue },
    GruvboxPurpleUnderline = { undercurl = c.undercurl, sp = p.purple },
    GruvboxAquaUnderline = { undercurl = c.undercurl, sp = p.aqua },
    GruvboxOrangeUnderline = { undercurl = c.undercurl, sp = p.orange },
    Normal = c.transparent_mode and { fg = p.fg1, bg = nil } or { fg = p.fg1, bg = p.bg0 },
    NormalFloat = c.transparent_mode and { fg = p.fg1, bg = nil } or { fg = p.fg1, bg = p.bg1 },
    NormalNC = c.dim_inactive and { fg = p.fg0, bg = p.bg1 } or { link = "Normal" },
    CursorLine = { bg = p.line3 },
    CursorColumn = { link = "CursorLine" },
    TabLineFill = { fg = p.bg4, bg = p.bg1, reverse = c.invert_tabline },
    TabLineSel = { fg = p.green, bg = p.bg1, reverse = c.invert_tabline },
    TabLine = { link = "TabLineFill" },
    MatchParen = { bg = p.bg3, bold = c.bold },
    ColorColumn = { bg = p.line3 },
    Conceal = { fg = p.blue },
    NonText = { link = "GruvboxBg2" },
    SpecialKey = { link = "GruvboxFg4" },
    Visual = { bg = p.bg3, reverse = c.invert_selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = p.yellow, bg = p.bg0, reverse = c.inverse },
    IncSearch = { fg = p.orange, bg = p.bg0, reverse = c.inverse },
    CurSearch = { link = "IncSearch" },
    QuickFixLine = { link = "GruvboxPurple" },
    Underlined = { fg = p.blue, underline = c.underline },
    StatusLine = { fg = p.bg2, bg = p.fg1, reverse = c.inverse },
    StatusLineNC = { fg = p.bg1, bg = p.fg4, reverse = c.inverse },
    WinBar = { fg = p.fg4, bg = p.bg0 },
    WinBarNC = { fg = p.fg3, bg = p.bg1 },
    WinSeparator = c.transparent_mode and { fg = p.line0, bg = nil } or { fg = p.line0, bg = p.bg0 },
    WildMenu = { fg = p.blue, bg = p.bg2, bold = c.bold },
    Directory = { link = "GruvboxGreenBold" },
    Title = { link = "GruvboxGreenBold" },
    ErrorMsg = { fg = p.bg0, bg = p.red, bold = c.bold },
    MoreMsg = { link = "GruvboxYellowBold" },
    ModeMsg = { link = "GruvboxYellowBold" },
    Question = { link = "GruvboxOrangeBold" },
    WarningMsg = { link = "GruvboxRedBold" },
    LineNr = { fg = p.bg4 },
    CursorLineNr = { fg = p.yellow, bg = p.line3 },
    SignColumn = c.transparent_mode and { bg = nil } or { bg = p.bg1 },
    Folded = { fg = p.gray, bg = p.bg1, italic = c.italic.folds },
    FoldColumn = c.transparent_mode and { fg = p.gray, bg = nil } or { fg = p.gray, bg = p.bg1 },
    Cursor = { reverse = c.inverse },
    vCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    Special = { link = "GruvboxOrange" },
    Comment = { fg = p.gray, italic = c.italic.comments },
    Todo = { fg = p.bg0, bg = p.yellow, bold = c.bold, italic = c.italic.comments },
    Done = { fg = p.orange, bold = c.bold, italic = c.italic.comments },
    Error = { fg = p.red, bold = c.bold, reverse = c.inverse },
    Constant = { link = "GruvboxPurple" },
    String = { fg = p.green, italic = c.italic.strings },
    Character = { link = "GruvboxPurple" },
    Boolean = { link = "GruvboxPurple" },
    Number = { link = "GruvboxPurple" },
    Float = { link = "GruvboxPurple" },
    Identifier = { link = "GruvboxBlue" },
    Function = { link = "GruvboxGreenBold" },
    Statement = { link = "GruvboxRed" },
    Conditional = { link = "GruvboxRed" },
    Repeat = { link = "GruvboxRed" },
    Label = { link = "GruvboxRed" },
    Operator = { fg = p.orange, italic = c.italic.operators },
    Keyword = { link = "GruvboxRed" },
    Exception = { link = "GruvboxRed" },
    PreProc = { link = "GruvboxAqua" },
    Include = { link = "GruvboxAqua" },
    Define = { link = "GruvboxAqua" },
    Macro = { link = "GruvboxAqua" },
    PreCondit = { link = "GruvboxAqua" },
    Type = { link = "GruvboxYellow" },
    StorageClass = { link = "GruvboxOrange" },
    Structure = { link = "GruvboxAqua" },
    Typedef = { link = "GruvboxYellow" },
    Pmenu = { fg = p.fg1, bg = p.bg2 },
    PmenuSel = { fg = p.bg2, bg = p.blue, bold = c.bold },
    PmenuSbar = { bg = p.bg2 },
    PmenuThumb = { bg = p.bg4 },
    DiffDelete = { bg = p.dim_red },
    DiffAdd = { bg = p.dim_green },
    DiffChange = { bg = p.dim_aqua },
    DiffText = { bg = p.yellow, fg = p.bg0 },
    SpellCap = { link = "GruvboxBlueUnderline" },
    SpellBad = { link = "GruvboxRedUnderline" },
    SpellLocal = { link = "GruvboxAquaUnderline" },
    SpellRare = { link = "GruvboxPurpleUnderline" },
    Whitespace = { fg = p.bg2 },
    Delimiter = { link = "GruvboxOrange" },
    EndOfBuffer = { link = "NonText" },
    DiagnosticError = { link = "GruvboxRed" },
    DiagnosticSignError = { link = "GruvboxRedSign" },
    DiagnosticUnderlineError = { link = "GruvboxRedUnderline" },
    DiagnosticWarn = { link = "GruvboxYellow" },
    DiagnosticSignWarn = { link = "GruvboxYellowSign" },
    DiagnosticUnderlineWarn = { link = "GruvboxYellowUnderline" },
    DiagnosticInfo = { link = "GruvboxBlue" },
    DiagnosticSignInfo = { link = "GruvboxBlueSign" },
    DiagnosticUnderlineInfo = { link = "GruvboxBlueUnderline" },
    DiagnosticHint = { link = "GruvboxAqua" },
    DiagnosticSignHint = { link = "GruvboxAquaSign" },
    DiagnosticUnderlineHint = { link = "GruvboxAquaUnderline" },
    DiagnosticFloatingError = { link = "GruvboxRed" },
    DiagnosticFloatingWarn = { link = "GruvboxOrange" },
    DiagnosticFloatingInfo = { link = "GruvboxBlue" },
    DiagnosticFloatingHint = { link = "GruvboxAqua" },
    DiagnosticVirtualTextError = { link = "GruvboxRed" },
    DiagnosticVirtualTextWarn = { link = "GruvboxYellow" },
    DiagnosticVirtualTextInfo = { link = "GruvboxBlue" },
    DiagnosticVirtualTextHint = { link = "GruvboxAqua" },
    DiagnosticOk = { link = "GruvboxGreenSign" },
    LspReferenceRead = { link = "GruvboxYellowBold" },
    LspReferenceText = { link = "GruvboxYellowBold" },
    LspReferenceWrite = { link = "GruvboxOrangeBold" },
    LspCodeLens = { link = "GruvboxGray" },
    LspSignatureActiveParameter = { link = "Search" },
    gitcommitSelectedFile = { link = "GruvboxGreen" },
    gitcommitDiscardedFile = { link = "GruvboxRed" },
    GitSignsAdd = { link = "GruvboxGreen" },
    GitSignsChange = { link = "GruvboxOrange" },
    GitSignsDelete = { link = "GruvboxRed" },
    NvimTreeSymlink = { fg = p.neutral_aqua },
    NvimTreeRootFolder = { fg = p.neutral_purple, bold = true },
    NvimTreeFolderIcon = { fg = p.neutral_blue, bold = true },
    NvimTreeFileIcon = { fg = p.fg2 },
    NvimTreeExecFile = { fg = p.neutral_green, bold = true },
    NvimTreeOpenedFile = { fg = p.red, bold = true },
    NvimTreeSpecialFile = { fg = p.neutral_yellow, bold = true, underline = true },
    NvimTreeImageFile = { fg = p.neutral_purple },
    NvimTreeIndentMarker = { fg = p.bg3 },
    NvimTreeGitDirty = { fg = p.neutral_yellow },
    NvimTreeGitStaged = { fg = p.neutral_yellow },
    NvimTreeGitMerge = { fg = p.neutral_purple },
    NvimTreeGitRenamed = { fg = p.neutral_purple },
    NvimTreeGitNew = { fg = p.neutral_yellow },
    NvimTreeGitDeleted = { fg = p.neutral_red },
    NvimTreeWindowPicker = { bg = p.aqua },
    debugPC = { link = "DiffAdd" },
    debugBreakpoint = { link = "GruvboxRedSign" },
    StartifyBracket = { link = "GruvboxFg3" },
    StartifyFile = { link = "GruvboxFg1" },
    StartifyNumber = { link = "GruvboxBlue" },
    StartifyPath = { link = "GruvboxGray" },
    StartifySlash = { link = "GruvboxGray" },
    StartifySection = { link = "GruvboxYellow" },
    StartifySpecial = { link = "GruvboxBg2" },
    StartifyHeader = { link = "GruvboxOrange" },
    StartifyFooter = { link = "GruvboxBg2" },
    StartifyVar = { link = "StartifyPath" },
    StartifySelect = { link = "Title" },
    DirvishPathTail = { link = "GruvboxAqua" },
    DirvishArg = { link = "GruvboxYellow" },
    netrwDir = { link = "GruvboxAqua" },
    netrwClassify = { link = "GruvboxAqua" },
    netrwLink = { link = "GruvboxGray" },
    netrwSymLink = { link = "GruvboxFg1" },
    netrwExe = { link = "GruvboxYellow" },
    netrwComment = { link = "GruvboxGray" },
    netrwList = { link = "GruvboxBlue" },
    netrwHelpCmd = { link = "GruvboxAqua" },
    netrwCmdSep = { link = "GruvboxFg3" },
    netrwVersion = { link = "GruvboxGreen" },
    NERDTreeDir = { link = "GruvboxAqua" },
    NERDTreeDirSlash = { link = "GruvboxAqua" },
    NERDTreeOpenable = { link = "GruvboxOrange" },
    NERDTreeClosable = { link = "GruvboxOrange" },
    NERDTreeFile = { link = "GruvboxFg1" },
    NERDTreeExecFile = { link = "GruvboxYellow" },
    NERDTreeUp = { link = "GruvboxGray" },
    NERDTreeCWD = { link = "GruvboxGreen" },
    NERDTreeHelp = { link = "GruvboxFg1" },
    NERDTreeToggleOn = { link = "GruvboxGreen" },
    NERDTreeToggleOff = { link = "GruvboxRed" },
    CocErrorSign = { link = "GruvboxRedSign" },
    CocWarningSign = { link = "GruvboxOrangeSign" },
    CocInfoSign = { link = "GruvboxBlueSign" },
    CocHintSign = { link = "GruvboxAquaSign" },
    CocErrorFloat = { link = "GruvboxRed" },
    CocWarningFloat = { link = "GruvboxOrange" },
    CocInfoFloat = { link = "GruvboxBlue" },
    CocHintFloat = { link = "GruvboxAqua" },
    CocDiagnosticsError = { link = "GruvboxRed" },
    CocDiagnosticsWarning = { link = "GruvboxOrange" },
    CocDiagnosticsInfo = { link = "GruvboxBlue" },
    CocDiagnosticsHint = { link = "GruvboxAqua" },
    CocSelectedText = { link = "GruvboxRed" },
    CocMenuSel = { link = "PmenuSel" },
    CocCodeLens = { link = "GruvboxGray" },
    CocErrorHighlight = { link = "GruvboxRedUnderline" },
    CocWarningHighlight = { link = "GruvboxOrangeUnderline" },
    CocInfoHighlight = { link = "GruvboxBlueUnderline" },
    CocHintHighlight = { link = "GruvboxAquaUnderline" },
    TelescopeNormal = { link = "GruvboxFg1" },
    TelescopeSelection = { link = "GruvboxOrangeBold" },
    TelescopeSelectionCaret = { link = "GruvboxRed" },
    TelescopeMultiSelection = { link = "GruvboxGray" },
    TelescopeBorder = { link = "TelescopeNormal" },
    TelescopePromptBorder = { link = "TelescopeNormal" },
    TelescopeResultsBorder = { link = "TelescopeNormal" },
    TelescopePreviewBorder = { link = "TelescopeNormal" },
    TelescopeMatching = { link = "GruvboxBlue" },
    TelescopePromptPrefix = { link = "GruvboxRed" },
    TelescopePrompt = { link = "TelescopeNormal" },
    CmpItemAbbr = { link = "GruvboxFg0" },
    CmpItemAbbrDeprecated = { link = "GruvboxFg1" },
    CmpItemAbbrMatch = { link = "GruvboxBlueBold" },
    CmpItemAbbrMatchFuzzy = { link = "GruvboxBlueUnderline" },
    CmpItemMenu = { link = "GruvboxGray" },
    CmpItemKindText = { link = "GruvboxOrange" },
    CmpItemKindVariable = { link = "GruvboxOrange" },
    CmpItemKindMethod = { link = "GruvboxBlue" },
    CmpItemKindFunction = { link = "GruvboxBlue" },
    CmpItemKindConstructor = { link = "GruvboxYellow" },
    CmpItemKindUnit = { link = "GruvboxBlue" },
    CmpItemKindField = { link = "GruvboxBlue" },
    CmpItemKindClass = { link = "GruvboxYellow" },
    CmpItemKindInterface = { link = "GruvboxYellow" },
    CmpItemKindModule = { link = "GruvboxBlue" },
    CmpItemKindProperty = { link = "GruvboxBlue" },
    CmpItemKindValue = { link = "GruvboxOrange" },
    CmpItemKindEnum = { link = "GruvboxYellow" },
    CmpItemKindOperator = { link = "GruvboxYellow" },
    CmpItemKindKeyword = { link = "GruvboxPurple" },
    CmpItemKindEvent = { link = "GruvboxPurple" },
    CmpItemKindReference = { link = "GruvboxPurple" },
    CmpItemKindColor = { link = "GruvboxPurple" },
    CmpItemKindSnippet = { link = "GruvboxGreen" },
    CmpItemKindFile = { link = "GruvboxBlue" },
    CmpItemKindFolder = { link = "GruvboxBlue" },
    CmpItemKindEnumMember = { link = "GruvboxAqua" },
    CmpItemKindConstant = { link = "GruvboxOrange" },
    CmpItemKindStruct = { link = "GruvboxYellow" },
    CmpItemKindTypeParameter = { link = "GruvboxYellow" },
    diffAdded = { link = "DiffAdd" },
    diffRemoved = { link = "DiffDelete" },
    diffChanged = { link = "DiffChange" },
    diffFile = { link = "GruvboxOrange" },
    diffNewFile = { link = "GruvboxYellow" },
    diffOldFile = { link = "GruvboxOrange" },
    diffLine = { link = "GruvboxBlue" },
    diffIndexLine = { link = "diffChanged" },
    NavicIconsFile = { link = "GruvboxBlue" },
    NavicIconsModule = { link = "GruvboxOrange" },
    NavicIconsNamespace = { link = "GruvboxBlue" },
    NavicIconsPackage = { link = "GruvboxAqua" },
    NavicIconsClass = { link = "GruvboxYellow" },
    NavicIconsMethod = { link = "GruvboxBlue" },
    NavicIconsProperty = { link = "GruvboxAqua" },
    NavicIconsField = { link = "GruvboxPurple" },
    NavicIconsConstructor = { link = "GruvboxBlue" },
    NavicIconsEnum = { link = "GruvboxPurple" },
    NavicIconsInterface = { link = "GruvboxGreen" },
    NavicIconsFunction = { link = "GruvboxBlue" },
    NavicIconsVariable = { link = "GruvboxPurple" },
    NavicIconsConstant = { link = "GruvboxOrange" },
    NavicIconsString = { link = "GruvboxGreen" },
    NavicIconsNumber = { link = "GruvboxOrange" },
    NavicIconsBoolean = { link = "GruvboxOrange" },
    NavicIconsArray = { link = "GruvboxOrange" },
    NavicIconsObject = { link = "GruvboxOrange" },
    NavicIconsKey = { link = "GruvboxAqua" },
    NavicIconsNull = { link = "GruvboxOrange" },
    NavicIconsEnumMember = { link = "GruvboxYellow" },
    NavicIconsStruct = { link = "GruvboxPurple" },
    NavicIconsEvent = { link = "GruvboxYellow" },
    NavicIconsOperator = { link = "GruvboxRed" },
    NavicIconsTypeParameter = { link = "GruvboxRed" },
    NavicText = { link = "GruvboxWhite" },
    NavicSeparator = { link = "GruvboxWhite" },
    htmlTag = { link = "GruvboxAquaBold" },
    htmlEndTag = { link = "GruvboxAquaBold" },
    htmlTagName = { link = "GruvboxBlue" },
    htmlArg = { link = "GruvboxOrange" },
    htmlTagN = { link = "GruvboxFg1" },
    htmlSpecialTagName = { link = "GruvboxBlue" },
    htmlLink = { fg = p.fg4, underline = c.underline },
    htmlSpecialChar = { link = "GruvboxRed" },
    htmlBold = { fg = p.fg0, bg = p.bg0, bold = c.bold },
    htmlBoldUnderline = { fg = p.fg0, bg = p.bg0, bold = c.bold, underline = c.underline },
    htmlBoldItalic = { fg = p.fg0, bg = p.bg0, bold = c.bold, italic = true },
    htmlBoldUnderlineItalic = {
      fg = p.fg0,
      bg = p.bg0,
      bold = c.bold,
      italic = true,
      underline = c.underline,
    },
    htmlUnderline = { fg = p.fg0, bg = p.bg0, underline = c.underline },
    htmlUnderlineItalic = {
      fg = p.fg0,
      bg = p.bg0,
      italic = true,
      underline = c.underline,
    },
    htmlItalic = { fg = p.fg0, bg = p.bg0, italic = true },
    xmlTag = { link = "GruvboxAquaBold" },
    xmlEndTag = { link = "GruvboxAquaBold" },
    xmlTagName = { link = "GruvboxBlue" },
    xmlEqual = { link = "GruvboxBlue" },
    docbkKeyword = { link = "GruvboxAquaBold" },
    xmlDocTypeDecl = { link = "GruvboxGray" },
    xmlDocTypeKeyword = { link = "GruvboxPurple" },
    xmlCdataStart = { link = "GruvboxGray" },
    xmlCdataCdata = { link = "GruvboxPurple" },
    dtdFunction = { link = "GruvboxGray" },
    dtdTagName = { link = "GruvboxPurple" },
    xmlAttrib = { link = "GruvboxOrange" },
    xmlProcessingDelim = { link = "GruvboxGray" },
    dtdParamEntityPunct = { link = "GruvboxGray" },
    dtdParamEntityDPunct = { link = "GruvboxGray" },
    xmlAttribPunct = { link = "GruvboxGray" },
    xmlEntity = { link = "GruvboxRed" },
    xmlEntityPunct = { link = "GruvboxRed" },
    clojureKeyword = { link = "GruvboxBlue" },
    clojureCond = { link = "GruvboxOrange" },
    clojureSpecial = { link = "GruvboxOrange" },
    clojureDefine = { link = "GruvboxOrange" },
    clojureFunc = { link = "GruvboxYellow" },
    clojureRepeat = { link = "GruvboxYellow" },
    clojureCharacter = { link = "GruvboxAqua" },
    clojureStringEscape = { link = "GruvboxAqua" },
    clojureException = { link = "GruvboxRed" },
    clojureRegexp = { link = "GruvboxAqua" },
    clojureRegexpEscape = { link = "GruvboxAqua" },
    clojureRegexpCharClass = { fg = p.fg3, bold = c.bold },
    clojureRegexpMod = { link = "clojureRegexpCharClass" },
    clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
    clojureParen = { link = "GruvboxFg3" },
    clojureAnonArg = { link = "GruvboxYellow" },
    clojureVariable = { link = "GruvboxBlue" },
    clojureMacro = { link = "GruvboxOrange" },
    clojureMeta = { link = "GruvboxYellow" },
    clojureDeref = { link = "GruvboxYellow" },
    clojureQuote = { link = "GruvboxYellow" },
    clojureUnquote = { link = "GruvboxYellow" },
    cOperator = { link = "GruvboxPurple" },
    cppOperator = { link = "GruvboxPurple" },
    cStructure = { link = "GruvboxOrange" },
    pythonBuiltin = { link = "GruvboxOrange" },
    pythonBuiltinObj = { link = "GruvboxOrange" },
    pythonBuiltinFunc = { link = "GruvboxOrange" },
    pythonFunction = { link = "GruvboxAqua" },
    pythonDecorator = { link = "GruvboxRed" },
    pythonInclude = { link = "GruvboxBlue" },
    pythonImport = { link = "GruvboxBlue" },
    pythonRun = { link = "GruvboxBlue" },
    pythonCoding = { link = "GruvboxBlue" },
    pythonOperator = { link = "GruvboxRed" },
    pythonException = { link = "GruvboxRed" },
    pythonExceptions = { link = "GruvboxPurple" },
    pythonBoolean = { link = "GruvboxPurple" },
    pythonDot = { link = "GruvboxFg3" },
    pythonConditional = { link = "GruvboxRed" },
    pythonRepeat = { link = "GruvboxRed" },
    pythonDottedName = { link = "GruvboxGreenBold" },
    cssBraces = { link = "GruvboxBlue" },
    cssFunctionName = { link = "GruvboxYellow" },
    cssIdentifier = { link = "GruvboxOrange" },
    cssClassName = { link = "GruvboxGreen" },
    cssColor = { link = "GruvboxBlue" },
    cssSelectorOp = { link = "GruvboxBlue" },
    cssSelectorOp2 = { link = "GruvboxBlue" },
    cssImportant = { link = "GruvboxGreen" },
    cssVendor = { link = "GruvboxFg1" },
    cssTextProp = { link = "GruvboxAqua" },
    cssAnimationProp = { link = "GruvboxAqua" },
    cssUIProp = { link = "GruvboxYellow" },
    cssTransformProp = { link = "GruvboxAqua" },
    cssTransitionProp = { link = "GruvboxAqua" },
    cssPrintProp = { link = "GruvboxAqua" },
    cssPositioningProp = { link = "GruvboxYellow" },
    cssBoxProp = { link = "GruvboxAqua" },
    cssFontDescriptorProp = { link = "GruvboxAqua" },
    cssFlexibleBoxProp = { link = "GruvboxAqua" },
    cssBorderOutlineProp = { link = "GruvboxAqua" },
    cssBackgroundProp = { link = "GruvboxAqua" },
    cssMarginProp = { link = "GruvboxAqua" },
    cssListProp = { link = "GruvboxAqua" },
    cssTableProp = { link = "GruvboxAqua" },
    cssFontProp = { link = "GruvboxAqua" },
    cssPaddingProp = { link = "GruvboxAqua" },
    cssDimensionProp = { link = "GruvboxAqua" },
    cssRenderProp = { link = "GruvboxAqua" },
    cssColorProp = { link = "GruvboxAqua" },
    cssGeneratedContentProp = { link = "GruvboxAqua" },
    javaScriptBraces = { link = "GruvboxFg1" },
    javaScriptFunction = { link = "GruvboxAqua" },
    javaScriptIdentifier = { link = "GruvboxRed" },
    javaScriptMember = { link = "GruvboxBlue" },
    javaScriptNumber = { link = "GruvboxPurple" },
    javaScriptNull = { link = "GruvboxPurple" },
    javaScriptParens = { link = "GruvboxFg3" },
    typescriptReserved = { link = "GruvboxAqua" },
    typescriptLabel = { link = "GruvboxAqua" },
    typescriptFuncKeyword = { link = "GruvboxAqua" },
    typescriptIdentifier = { link = "GruvboxOrange" },
    typescriptBraces = { link = "GruvboxFg1" },
    typescriptEndColons = { link = "GruvboxFg1" },
    typescriptDOMObjects = { link = "GruvboxFg1" },
    typescriptAjaxMethods = { link = "GruvboxFg1" },
    typescriptLogicSymbols = { link = "GruvboxFg1" },
    typescriptDocSeeTag = { link = "Comment" },
    typescriptDocParam = { link = "Comment" },
    typescriptDocTags = { link = "vimCommentTitle" },
    typescriptGlobalObjects = { link = "GruvboxFg1" },
    typescriptParens = { link = "GruvboxFg3" },
    typescriptOpSymbols = { link = "GruvboxFg3" },
    typescriptHtmlElemProperties = { link = "GruvboxFg1" },
    typescriptNull = { link = "GruvboxPurple" },
    typescriptInterpolationDelimiter = { link = "GruvboxAqua" },
    purescriptModuleKeyword = { link = "GruvboxAqua" },
    purescriptModuleName = { link = "GruvboxFg1" },
    purescriptWhere = { link = "GruvboxAqua" },
    purescriptDelimiter = { link = "GruvboxFg4" },
    purescriptType = { link = "GruvboxFg1" },
    purescriptImportKeyword = { link = "GruvboxAqua" },
    purescriptHidingKeyword = { link = "GruvboxAqua" },
    purescriptAsKeyword = { link = "GruvboxAqua" },
    purescriptStructure = { link = "GruvboxAqua" },
    purescriptOperator = { link = "GruvboxBlue" },
    purescriptTypeVar = { link = "GruvboxFg1" },
    purescriptConstructor = { link = "GruvboxFg1" },
    purescriptFunction = { link = "GruvboxFg1" },
    purescriptConditional = { link = "GruvboxOrange" },
    purescriptBacktick = { link = "GruvboxOrange" },
    coffeeExtendedOp = { link = "GruvboxFg3" },
    coffeeSpecialOp = { link = "GruvboxFg3" },
    coffeeCurly = { link = "GruvboxOrange" },
    coffeeParen = { link = "GruvboxFg3" },
    coffeeBracket = { link = "GruvboxOrange" },
    rubyStringDelimiter = { link = "GruvboxGreen" },
    rubyInterpolationDelimiter = { link = "GruvboxAqua" },
    rubyDefinedOperator = { link = "rubyKeyword" },
    objcTypeModifier = { link = "GruvboxRed" },
    objcDirective = { link = "GruvboxBlue" },
    goDirective = { link = "GruvboxAqua" },
    goConstants = { link = "GruvboxPurple" },
    goDeclaration = { link = "GruvboxRed" },
    goDeclType = { link = "GruvboxBlue" },
    goBuiltins = { link = "GruvboxOrange" },
    luaIn = { link = "GruvboxRed" },
    luaFunction = { link = "GruvboxAqua" },
    luaTable = { link = "GruvboxOrange" },
    moonSpecialOp = { link = "GruvboxFg3" },
    moonExtendedOp = { link = "GruvboxFg3" },
    moonFunction = { link = "GruvboxFg3" },
    moonObject = { link = "GruvboxYellow" },
    javaAnnotation = { link = "GruvboxBlue" },
    javaDocTags = { link = "GruvboxAqua" },
    javaCommentTitle = { link = "vimCommentTitle" },
    javaParen = { link = "GruvboxFg3" },
    javaParen1 = { link = "GruvboxFg3" },
    javaParen2 = { link = "GruvboxFg3" },
    javaParen3 = { link = "GruvboxFg3" },
    javaParen4 = { link = "GruvboxFg3" },
    javaParen5 = { link = "GruvboxFg3" },
    javaOperator = { link = "GruvboxOrange" },
    javaVarArg = { link = "GruvboxGreen" },
    elixirDocString = { link = "Comment" },
    elixirStringDelimiter = { link = "GruvboxGreen" },
    elixirInterpolationDelimiter = { link = "GruvboxAqua" },
    elixirModuleDeclaration = { link = "GruvboxYellow" },
    scalaNameDefinition = { link = "GruvboxFg1" },
    scalaCaseFollowing = { link = "GruvboxFg1" },
    scalaCapitalWord = { link = "GruvboxFg1" },
    scalaTypeExtension = { link = "GruvboxFg1" },
    scalaKeyword = { link = "GruvboxRed" },
    scalaKeywordModifier = { link = "GruvboxRed" },
    scalaSpecial = { link = "GruvboxAqua" },
    scalaOperator = { link = "GruvboxFg1" },
    scalaTypeDeclaration = { link = "GruvboxYellow" },
    scalaTypeTypePostDeclaration = { link = "GruvboxYellow" },
    scalaInstanceDeclaration = { link = "GruvboxFg1" },
    scalaInterpolation = { link = "GruvboxAqua" },
    markdownItalic = { fg = p.fg3, italic = true },
    markdownBold = { fg = p.fg3, bold = c.bold },
    markdownBoldItalic = { fg = p.fg3, bold = c.bold, italic = true },
    markdownH1 = { link = "GruvboxGreenBold" },
    markdownH2 = { link = "GruvboxGreenBold" },
    markdownH3 = { link = "GruvboxYellowBold" },
    markdownH4 = { link = "GruvboxYellowBold" },
    markdownH5 = { link = "GruvboxYellow" },
    markdownH6 = { link = "GruvboxYellow" },
    markdownCode = { link = "GruvboxAqua" },
    markdownCodeBlock = { link = "GruvboxAqua" },
    markdownCodeDelimiter = { link = "GruvboxAqua" },
    markdownBlockquote = { link = "GruvboxGray" },
    markdownListMarker = { link = "GruvboxGray" },
    markdownOrderedListMarker = { link = "GruvboxGray" },
    markdownRule = { link = "GruvboxGray" },
    markdownHeadingRule = { link = "GruvboxGray" },
    markdownUrlDelimiter = { link = "GruvboxFg3" },
    markdownLinkDelimiter = { link = "GruvboxFg3" },
    markdownLinkTextDelimiter = { link = "GruvboxFg3" },
    markdownHeadingDelimiter = { link = "GruvboxOrange" },
    markdownUrl = { link = "GruvboxPurple" },
    markdownUrlTitleDelimiter = { link = "GruvboxGreen" },
    markdownLinkText = { fg = p.gray, underline = c.underline },
    markdownIdDeclaration = { link = "markdownLinkText" },
    haskellType = { link = "GruvboxBlue" },
    haskellIdentifier = { link = "GruvboxAqua" },
    haskellSeparator = { link = "GruvboxFg4" },
    haskellDelimiter = { link = "GruvboxOrange" },
    haskellOperators = { link = "GruvboxPurple" },
    haskellBacktick = { link = "GruvboxOrange" },
    haskellStatement = { link = "GruvboxPurple" },
    haskellConditional = { link = "GruvboxPurple" },
    haskellLet = { link = "GruvboxRed" },
    haskellDefault = { link = "GruvboxRed" },
    haskellWhere = { link = "GruvboxRed" },
    haskellBottom = { link = "GruvboxRedBold" },
    haskellImportKeywords = { link = "GruvboxPurpleBold" },
    haskellDeclKeyword = { link = "GruvboxOrange" },
    haskellDecl = { link = "GruvboxOrange" },
    haskellDeriving = { link = "GruvboxPurple" },
    haskellAssocType = { link = "GruvboxAqua" },
    haskellNumber = { link = "GruvboxAqua" },
    haskellPragma = { link = "GruvboxRedBold" },
    haskellTH = { link = "GruvboxAquaBold" },
    haskellForeignKeywords = { link = "GruvboxGreen" },
    haskellKeyword = { link = "GruvboxRed" },
    haskellFloat = { link = "GruvboxAqua" },
    haskellInfix = { link = "GruvboxPurple" },
    haskellQuote = { link = "GruvboxGreenBold" },
    haskellShebang = { link = "GruvboxYellowBold" },
    haskellLiquid = { link = "GruvboxPurpleBold" },
    haskellQuasiQuoted = { link = "GruvboxBlueBold" },
    haskellRecursiveDo = { link = "GruvboxPurple" },
    haskellQuotedType = { link = "GruvboxRed" },
    haskellPreProc = { link = "GruvboxFg4" },
    haskellTypeRoles = { link = "GruvboxRedBold" },
    haskellTypeForall = { link = "GruvboxRed" },
    haskellPatternKeyword = { link = "GruvboxBlue" },
    jsonKeyword = { link = "GruvboxGreen" },
    jsonQuote = { link = "GruvboxGreen" },
    jsonBraces = { link = "GruvboxFg1" },
    jsonString = { link = "GruvboxFg1" },
    mailQuoted1 = { link = "GruvboxAqua" },
    mailQuoted2 = { link = "GruvboxPurple" },
    mailQuoted3 = { link = "GruvboxYellow" },
    mailQuoted4 = { link = "GruvboxGreen" },
    mailQuoted5 = { link = "GruvboxRed" },
    mailQuoted6 = { link = "GruvboxOrange" },
    mailSignature = { link = "Comment" },
    csBraces = { link = "GruvboxFg1" },
    csEndColon = { link = "GruvboxFg1" },
    csLogicSymbols = { link = "GruvboxFg1" },
    csParens = { link = "GruvboxFg3" },
    csOpSymbols = { link = "GruvboxFg3" },
    csInterpolationDelimiter = { link = "GruvboxFg3" },
    csInterpolationAlignDel = { link = "GruvboxAquaBold" },
    csInterpolationFormat = { link = "GruvboxAqua" },
    csInterpolationFormatDel = { link = "GruvboxAquaBold" },
    rustSigil = { link = "GruvboxOrange" },
    rustEscape = { link = "GruvboxAqua" },
    rustStringContinuation = { link = "GruvboxAqua" },
    rustEnum = { link = "GruvboxAqua" },
    rustStructure = { link = "GruvboxAqua" },
    rustModPathSep = { link = "GruvboxFg2" },
    rustCommentLineDoc = { link = "Comment" },
    rustDefault = { link = "GruvboxAqua" },
    ocamlOperator = { link = "GruvboxFg1" },
    ocamlKeyChar = { link = "GruvboxOrange" },
    ocamlArrow = { link = "GruvboxOrange" },
    ocamlInfixOpKeyword = { link = "GruvboxRed" },
    ocamlConstructor = { link = "GruvboxOrange" },
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaCodeActionBorder = { link = "GruvboxFg1" },
    LspSagaCodeActionContent = { fg = p.green, bold = c.bold },
    LspSagaLspFinderBorder = { link = "GruvboxFg1" },
    LspSagaAutoPreview = { link = "GruvboxOrange" },
    TargetWord = { fg = p.blue, bold = c.bold },
    FinderSeparator = { link = "GruvboxAqua" },
    LspSagaDefPreviewBorder = { link = "GruvboxBlue" },
    LspSagaHoverBorder = { link = "GruvboxOrange" },
    LspSagaRenameBorder = { link = "GruvboxBlue" },
    LspSagaDiagnosticSource = { link = "GruvboxOrange" },
    LspSagaDiagnosticBorder = { link = "GruvboxPurple" },
    LspSagaDiagnosticHeader = { link = "GruvboxGreen" },
    LspSagaSignatureHelpBorder = { link = "GruvboxGreen" },
    SagaShadow = { link = "GruvboxBg0" },
    DashboardShortCut = { link = "GruvboxOrange" },
    DashboardHeader = { link = "GruvboxAqua" },
    DashboardCenter = { link = "GruvboxYellow" },
    DashboardFooter = { fg = p.purple, italic = true },
    MasonHighlight = { link = "GruvboxAqua" },
    MasonHighlightBlock = { fg = p.bg0, bg = p.blue },
    MasonHighlightBlockBold = { fg = p.bg0, bg = p.blue, bold = true },
    MasonHighlightSecondary = { fg = p.yellow },
    MasonHighlightBlockSecondary = { fg = p.bg0, bg = p.yellow },
    MasonHighlightBlockBoldSecondary = { fg = p.bg0, bg = p.yellow, bold = true },
    MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
    MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
    MasonMuted = { fg = p.fg4 },
    MasonMutedBlock = { fg = p.bg0, bg = p.fg4 },
    MasonMutedBlockBold = { fg = p.bg0, bg = p.fg4, bold = true },
    LspInlayHint = { link = "comment" },
    CarbonFile = { link = "GruvboxFg1" },
    CarbonExe = { link = "GruvboxYellow" },
    CarbonSymlink = { link = "GruvboxAqua" },
    CarbonBrokenSymlink = { link = "GruvboxRed" },
    CarbonIndicator = { link = "GruvboxGray" },
    CarbonDanger = { link = "GruvboxRed" },
    CarbonPending = { link = "GruvboxYellow" },
    NoiceCursor = { link = "TermCursor" },
    NotifyDEBUGBorder = { link = "GruvboxBlue" },
    NotifyDEBUGIcon = { link = "GruvboxBlue" },
    NotifyDEBUGTitle = { link = "GruvboxBlue" },
    NotifyERRORBorder = { link = "GruvboxRed" },
    NotifyERRORIcon = { link = "GruvboxRed" },
    NotifyERRORTitle = { link = "GruvboxRed" },
    NotifyINFOBorder = { link = "GruvboxAqua" },
    NotifyINFOIcon = { link = "GruvboxAqua" },
    NotifyINFOTitle = { link = "GruvboxAqua" },
    NotifyTRACEBorder = { link = "GruvboxGreen" },
    NotifyTRACEIcon = { link = "GruvboxGreen" },
    NotifyTRACETitle = { link = "GruvboxGreen" },
    NotifyWARNBorder = { link = "GruvboxYellow" },
    NotifyWARNIcon = { link = "GruvboxYellow" },
    NotifyWARNTitle = { link = "GruvboxYellow" },
    IlluminatedWordText = { link = "LspReferenceText" },
    IlluminatedWordRead = { link = "LspReferenceRead" },
    IlluminatedWordWrite = { link = "LspReferenceWrite" },
    TSRainbowRed = { fg = p.red },
    TSRainbowOrange = { fg = p.orange },
    TSRainbowYellow = { fg = p.yellow },
    TSRainbowGreen = { fg = p.green },
    TSRainbowBlue = { fg = p.blue },
    TSRainbowViolet = { fg = p.purple },
    TSRainbowCyan = { fg = p.aqua },
    RainbowDelimiterRed = { fg = p.red },
    RainbowDelimiterOrange = { fg = p.orange },
    RainbowDelimiterYellow = { fg = p.yellow },
    RainbowDelimiterGreen = { fg = p.green },
    RainbowDelimiterBlue = { fg = p.blue },
    RainbowDelimiterViolet = { fg = p.purple },
    RainbowDelimiterCyan = { fg = p.aqua },
    DapBreakpointSymbol = { fg = p.red, bg = p.bg1 },
    DapStoppedSymbol = { fg = p.green, bg = p.bg1 },
    DapUIBreakpointsCurrentLine = { link = "GruvboxYellow" },
    DapUIBreakpointsDisabledLine = { link = "GruvboxGray" },
    DapUIBreakpointsInfo = { link = "GruvboxAqua" },
    DapUIBreakpointsLine = { link = "GruvboxYellow" },
    DapUIBreakpointsPath = { link = "GruvboxBlue" },
    DapUICurrentFrameName = { link = "GruvboxPurple" },
    DapUIDecoration = { link = "GruvboxPurple" },
    DapUIEndofBuffer = { link = "EndOfBuffer" },
    DapUIFloatBorder = { link = "GruvboxAqua" },
    DapUILineNumber = { link = "GruvboxYellow" },
    DapUIModifiedValue = { link = "GruvboxRed" },
    DapUIPlayPause = { fg = p.green, bg = p.bg1 },
    DapUIRestart = { fg = p.green, bg = p.bg1 },
    DapUIScope = { link = "GruvboxBlue" },
    DapUISource = { link = "GruvboxFg1" },
    DapUIStepBack = { fg = p.blue, bg = p.bg1 },
    DapUIStepInto = { fg = p.blue, bg = p.bg1 },
    DapUIStepOut = { fg = p.blue, bg = p.bg1 },
    DapUIStepOver = { fg = p.blue, bg = p.bg1 },
    DapUIStop = { fg = p.red, bg = p.bg1 },
    DapUIStoppedThread = { link = "GruvboxBlue" },
    DapUIThread = { link = "GruvboxBlue" },
    DapUIType = { link = "GruvboxOrange" },
    DapUIUnavailable = { link = "GruvboxGray" },
    DapUIWatchesEmpty = { link = "GruvboxGray" },
    DapUIWatchesError = { link = "GruvboxRed" },
    DapUIWatchesValue = { link = "GruvboxYellow" },
    DapUIWinSelect = { link = "GruvboxYellow" },
    NeogitDiffDelete = { link = "DiffDelete" },
    NeogitDiffAdd = { link = "DiffAdd" },
    NeogitHunkHeader = { link = "WinBar" },
    NeogitHunkHeaderHighlight = { link = "WinBarNC" },
    DiffviewStatusModified = { link = "GruvboxGreenBold" },
    DiffviewFilePanelInsertions = { link = "GruvboxGreenBold" },
    DiffviewFilePanelDeletions = { link = "GruvboxRedBold" },
    MiniAnimateCursor = { reverse = true, nocombine = true },
    MiniAnimateNormalFloat = { fg = p.fg1, bg = p.bg1 },
    MiniClueBorder = { link = "FloatBorder" },
    MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
    MiniClueDescSingle = { link = "NormalFloat" },
    MiniClueNextKey = { link = "DiagnosticFloatingHint" },
    MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
    MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
    MiniClueTitle = { link = "FloatTitle" },
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword = { underline = true },
    MiniCursorwordCurrent = { underline = true },
    MiniDepsChangeAdded = { link = "GruvboxGreen" },
    MiniDepsChangeRemoved = { link = "GruvboxRed" },
    MiniDepsHint = { link = "DiagnosticHint" },
    MiniDepsInfo = { link = "DiagnosticInfo" },
    MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
    MiniDepsPlaceholder = { link = "Comment" },
    MiniDepsTitle = { link = "Title" },
    MiniDepsTitleError = { link = "DiffDelete" },
    MiniDepsTitleSame = { link = "DiffChange" },
    MiniDepsTitleUpdate = { link = "DiffAdd" },
    MiniDiffOverAdd = { link = "DiffAdd" },
    MiniDiffOverChange = { link = "DiffText" },
    MiniDiffOverContext = { link = "DiffChange" },
    MiniDiffOverDelete = { link = "DiffDelete" },
    MiniDiffSignAdd = { link = "GruvboxGreen" },
    MiniDiffSignChange = { link = "GruvboxAqua" },
    MiniDiffSignDelete = { link = "GruvboxRed" },
    MiniFilesBorder = { link = "FloatBorder" },
    MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
    MiniFilesCursorLine = { bg = p.bg2 },
    MiniFilesDirectory = { link = "Directory" },
    MiniFilesFile = { link = "GruvboxFg1" },
    MiniFilesNormal = { link = "NormalFloat" },
    MiniFilesTitle = { link = "FloatTitle" },
    MiniFilesTitleFocused = { link = "GruvboxOrangeBold" },
    MiniHipatternsFixme = { fg = p.bg0, bg = p.red, bold = c.bold },
    MiniHipatternsHack = { fg = p.bg0, bg = p.yellow, bold = c.bold },
    MiniHipatternsNote = { fg = p.bg0, bg = p.blue, bold = c.bold },
    MiniHipatternsTodo = { fg = p.bg0, bg = p.aqua, bold = c.bold },
    MiniIconsAzure = { link = "GruvboxBlue" },
    MiniIconsBlue = { link = "GruvboxBlue" },
    MiniIconsCyan = { link = "GruvboxAqua" },
    MiniIconsGreen = { link = "GruvboxGreen" },
    MiniIconsGrey = { link = "GruvboxFg0" },
    MiniIconsOrange = { link = "GruvboxOrange" },
    MiniIconsPurple = { link = "GruvboxPurple" },
    MiniIconsRed = { link = "GruvboxRed" },
    MiniIconsYellow = { link = "GruvboxYellow" },
    MiniIndentscopeSymbol = { fg = p.line1 },
    MiniIndentscopeSymbolOff = { link = "GruvboxYellow" },
    MiniJump = { link = "GruvboxOrangeUnderline" },
    MiniJump2dDim = { link = "GruvboxGray" },
    MiniJump2dSpot = { fg = p.orange, bold = c.bold, nocombine = true },
    MiniJump2dSpotAhead = { fg = p.aqua, bg = p.bg0, nocombine = true },
    MiniJump2dSpotUnique = { fg = p.yellow, bold = c.bold, nocombine = true },
    MiniMapNormal = { link = "NormalFloat" },
    MiniMapSymbolCount = { link = "Special" },
    MiniMapSymbolLine = { link = "Title" },
    MiniMapSymbolView = { link = "Delimiter" },
    MiniNotifyBorder = { link = "FloatBorder" },
    MiniNotifyNormal = { link = "NormalFloat" },
    MiniNotifyTitle = { link = "FloatTitle" },
    MiniOperatorsExchangeFrom = { link = "IncSearch" },
    MiniPickBorder = { link = "FloatBorder" },
    MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
    MiniPickBorderText = { link = "FloatTitle" },
    MiniPickIconDirectory = { link = "Directory" },
    MiniPickIconFile = { link = "MiniPickNormal" },
    MiniPickHeader = { link = "DiagnosticFloatingHint" },
    MiniPickMatchCurrent = { bg = p.bg2 },
    MiniPickMatchMarked = { link = "Visual" },
    MiniPickMatchRanges = { link = "DiagnosticFloatingHint" },
    MiniPickNormal = { link = "NormalFloat" },
    MiniPickPreviewLine = { link = "CursorLine" },
    MiniPickPreviewRegion = { link = "IncSearch" },
    MiniPickPrompt = { link = "DiagnosticFloatingInfo" },
    MiniStarterCurrent = { nocombine = true },
    MiniStarterFooter = { link = "GruvboxGray" },
    MiniStarterHeader = { link = "Title" },
    MiniStarterInactive = { link = "Comment" },
    MiniStarterItem = { link = "Normal" },
    MiniStarterItemBullet = { link = "Delimiter" },
    MiniStarterItemPrefix = { link = "WarningMsg" },
    MiniStarterSection = { link = "Delimiter" },
    MiniStarterQuery = { link = "MoreMsg" },
    MiniStatuslineDevinfo = { link = "StatusLine" },
    MiniStatuslineFileinfo = { link = "StatusLine" },
    MiniStatuslineFilename = { link = "StatusLineNC" },
    MiniStatuslineInactive = { link = "StatusLineNC" },
    MiniStatuslineModeCommand = { fg = p.bg0, bg = p.yellow, bold = c.bold },
    MiniStatuslineModeInsert = { fg = p.bg0, bg = p.blue, bold = c.bold },
    MiniStatuslineModeNormal = { fg = p.bg0, bg = p.fg1, bold = c.bold },
    MiniStatuslineModeOther = { fg = p.bg0, bg = p.aqua, bold = c.bold },
    MiniStatuslineModeReplace = { fg = p.bg0, bg = p.red, bold = c.bold },
    MiniStatuslineModeVisual = { fg = p.bg0, bg = p.green, bold = c.bold },
    MiniSurround = { link = "IncSearch" },
    MiniTablineCurrent = { fg = p.green, bg = p.bg1, bold = c.bold, reverse = c.invert_tabline },
    MiniTablineFill = { link = "TabLineFill" },
    MiniTablineHidden = { fg = p.bg4, bg = p.bg1, reverse = c.invert_tabline },
    MiniTablineModifiedCurrent = {
      fg = p.bg1,
      bg = p.green,
      bold = c.bold,
      reverse = c.invert_tabline,
    },
    MiniTablineModifiedHidden = { fg = p.bg1, bg = p.bg4, reverse = c.invert_tabline },
    MiniTablineModifiedVisible = { fg = p.bg1, bg = p.fg1, reverse = c.invert_tabline },
    MiniTablineTabpagesection = { link = "Search" },
    MiniTablineVisible = { fg = p.fg1, bg = p.bg1, reverse = c.invert_tabline },
    MiniTestEmphasis = { bold = c.bold },
    MiniTestFail = { link = "GruvboxRedBold" },
    MiniTestPass = { link = "GruvboxGreenBold" },
    MiniTrailspace = { bg = p.red },
    IblIndent = { fg = p.line2 },
    ["@comment"] = { link = "Comment" },
    ["@none"] = { bg = "NONE", fg = "NONE" },
    ["@preproc"] = { link = "PreProc" },
    ["@define"] = { link = "Define" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { link = "String" },
    ["@string.regexp"] = { link = "String" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@string.special.path"] = { link = "Underlined" },
    ["@string.special.symbol"] = { link = "Identifier" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { link = "Special" },
    ["@parameter"] = { link = "Identifier" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { link = "GruvboxRed" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@debug"] = { link = "Debug" },
    ["@label"] = { link = "Label" },
    ["@include"] = { link = "Include" },
    ["@exception"] = { link = "Exception" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@attribute"] = { link = "PreProc" },
    ["@field"] = { link = "Identifier" },
    ["@property"] = { link = "Identifier" },
    ["@variable"] = { link = "GruvboxFg1" },
    ["@variable.builtin"] = { link = "Special" },
    ["@variable.member"] = { link = "Identifier" },
    ["@variable.parameter"] = { link = "Identifier" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@markup"] = { link = "GruvboxFg1" },
    ["@markup.strong"] = { bold = c.bold },
    ["@markup.italic"] = { link = "@text.emphasis" },
    ["@markup.underline"] = { underline = c.underline },
    ["@markup.strikethrough"] = { strikethrough = c.strikethrough },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.raw"] = { link = "String" },
    ["@markup.math"] = { link = "Special" },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.link"] = { link = "Underlined" },
    ["@markup.link.label"] = { link = "SpecialChar" },
    ["@markup.list"] = { link = "Delimiter" },
    ["@markup.list.checked"] = { link = "GruvboxGreen" },
    ["@markup.list.unchecked"] = { link = "GruvboxGray" },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.note"] = { link = "SpecialComment" },
    ["@comment.warning"] = { link = "WarningMsg" },
    ["@comment.error"] = { link = "ErrorMsg" },
    ["@diff.plus"] = { link = "diffAdded" },
    ["@diff.minus"] = { link = "diffRemoved" },
    ["@diff.delta"] = { link = "diffChanged" },
    ["@module"] = { link = "GruvboxFg1" },
    ["@namespace"] = { link = "GruvboxFg1" },
    ["@symbol"] = { link = "Identifier" },
    ["@text"] = { link = "GruvboxFg1" },
    ["@text.strong"] = { bold = c.bold },
    ["@text.emphasis"] = { italic = c.italic.emphasis },
    ["@text.underline"] = { underline = c.underline },
    ["@text.strike"] = { strikethrough = c.strikethrough },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference"] = { link = "Constant" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.checked"] = { link = "GruvboxGreen" },
    ["@text.todo.unchecked"] = { link = "GruvboxGray" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { fg = p.purple, bold = c.bold },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = p.fg0, bg = p.red, bold = c.bold },
    ["@text.diff.add"] = { link = "diffAdded" },
    ["@text.diff.delete"] = { link = "diffRemoved" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@macro"] = { link = "Macro" },
    ["@structure"] = { link = "Structure" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@macro" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@constructor" },
    ["@lsp.type.macro"] = { link = "@macro" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
  }

  for group, hl in pairs(c.overrides) do
    if groups[group] then
      -- "link" should not mix with other configs (:h hi-link)
      groups[group].link = nil
    end

    groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
  end

  return groups
end

---@param config GruvboxConfig?
Gruvbox.setup = function(config)
  Gruvbox.config = vim.tbl_deep_extend("force", Gruvbox.config, config or {})
end

--- main load function
Gruvbox.load = function()
  -- reset colors
  if vim.g.colors_name then
    vim.cmd.hi("clear")
  end
  vim.g.colors_name = "gruvbox"
  vim.o.termguicolors = true

  local config = Gruvbox.config
  local palette = get_palette(config)

  if config.terminal_colors then
    local term_colors = {
      palette.bg0,
      palette.neutral_red,
      palette.neutral_green,
      palette.neutral_yellow,
      palette.neutral_blue,
      palette.neutral_purple,
      palette.neutral_aqua,
      palette.fg4,
      palette.gray,
      palette.red,
      palette.green,
      palette.yellow,
      palette.blue,
      palette.purple,
      palette.aqua,
      palette.fg1,
    }
    for index, value in ipairs(term_colors) do
      vim.g["terminal_color_" .. index - 1] = value
    end
  end

  for group, settings in pairs(build_hls(config, palette)) do
    vim.api.nvim_set_hl(0, group, settings)
  end
end

return Gruvbox
